<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <IsPackable>false</IsPackable>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <TestingPlatformDotnetTestSupport>true</TestingPlatformDotnetTestSupport>
    <UseAppHost>false</UseAppHost>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.InMemory" Version="10.0.0" />
    <PackageReference Include="Microsoft.Extensions.TimeProvider.Testing" Version="10.8.0" />
    <PackageReference Include="TUnit" Version="1.63.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Extensions.Options.EntityFrameworkCore\Extensions.Options.EntityFrameworkCore.csproj" />
  </ItemGroup>

</Project>
